test: add test for checking if not operator
This is a work in progress.

```
$ bin/imba test/index.imba
/Users/ccscanf/src/github.com/imba/imba.git/test/syntax/conditionals.imba:45
			if (((self.setCondition(v_ = self.condition() n 1),v_)) - 1) {
			                                            ^

SyntaxError: missing ) after argument list
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.require.extensions..imba (/Users/ccscanf/src/github.com/imba/imba.git/register.js:60:14)
    at Module.load (/Users/ccscanf/src/github.com/imba/imba.git/register.js:83:26)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/ccscanf/src/github.com/imba/imba.git/test/index.imba:25:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.exports.run.self.run (/Users/ccscanf/src/github.com/imba/imba.git/lib/compiler/index.js:48:15)
error Command failed with exit code 1.
```