tag: add error message when tags are used but unexported
The default error message for this is cryptic

```
[...]
imba/dom/tag.js:1207
    if (type.substr(0,4) == 'svg:') {

TypeError: Cannot read property 'substr' of undefined
[...]
```

Now it says

```
imba/dom/tag.js:1206
		throw ("Expected a valid tag but got falsy type, did you forget to export it?");
		^
Expected a valid tag but got falsy type, did you forget to export it?
[...]
```

Closes: #236 (Improve error message when importing private tag)